openapi: 3.0.3
info:
  title: Prunk Services API
  description: Serverless API for Prunk Services
  version: 1.0.0
  contact:
    name: Prunk Services Team
    email: support@prunk.com
  license:
    name: ISC
    url: https://opensource.org/licenses/ISC

servers:
  - url: https://{apiId}.execute-api.ap-northeast-1.amazonaws.com/{stage}
    description: Production server
    variables:
      apiId:
        description: API Gateway ID
        default: your-api-gateway-id
      stage:
        description: Deployment stage
        default: dev
  - url: http://localhost:3000
    description: Local development server

paths:
  /hello:
    get:
      summary: Hello World endpoint
      description: Returns a simple hello world message
      operationId: getHello
      tags:
        - Health
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: 'Hello from Prunk Services!'
                  timestamp:
                    type: string
                    format: date-time
                    example: '2024-01-15T10:30:00Z'
                  stage:
                    type: string
                    example: 'dev'
                required:
                  - message
                  - timestamp
                  - stage
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /project:
    get:
      summary: Get user's projects
      description: Retrieve all projects that the authenticated user has access to
      operationId: getProjects
      tags:
        - Projects
      security:
        - BearerAuth: []
      parameters:
        - name: page_size
          in: query
          description: Number of projects to return (1-100)
          required: false
          schema:
            type: integer
            minimum: 1
            maximum: 100
            default: 10
        - name: last_evaluated_key
          in: query
          description: Pagination token for getting the next page of results
          required: false
          schema:
            type: string
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  records:
                    type: array
                    items:
                      $ref: '#/components/schemas/Project'
                  lastEvaluatedKey:
                    type: string
                    nullable: true
                    description: Pagination token for the next page
                required:
                  - records
                  - lastEvaluatedKey
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
    
    post:
      summary: Create a new project
      description: Create a new project and assign the authenticated user as the owner
      operationId: createProject
      tags:
        - Projects
      security:
        - BearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  minLength: 1
                  description: The name of the project
                  example: 'My New Project'
                description:
                  type: string
                  description: The description of the project
                  example: 'A description of my new project'
                status:
                  type: string
                  enum: ['ACTIVE', 'SUSPENDED']
                  default: 'ACTIVE'
                  description: The status of the project
                preferences:
                  type: object
                  description: The preferences of the project
                  example: {}
              required:
                - name
                - description
      responses:
        '200':
          description: Project created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Project'
        '400':
          description: Bad request - invalid project data
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /project/{project_id}:
    get:
      summary: Get project details
      description: Retrieve details of a specific project that the authenticated user has access to
      operationId: getProject
      tags:
        - Projects
      security:
        - BearerAuth: []
      parameters:
        - name: project_id
          in: path
          description: The ID of the project to get
          required: true
          schema:
            type: string
            minLength: 1
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Project'
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '404':
          description: Project not found or access denied
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
      x-amazon-apigateway-integration:
        type: aws_proxy
        httpMethod: POST
        uri: arn:aws:apigateway:ap-northeast-1:lambda:path/2015-03-31/functions/arn:aws:lambda:ap-northeast-1:{accountId}:function:prunk-services-{stage}-hello/invocations
        credentials: arn:aws:iam::{accountId}:role/apigateway-lambda-role
        requestTemplates:
          application/json: |
            {
              "body": $input.json('$'),
              "headers": {
                #foreach($header in $input.params().header.keySet())
                "$header": "$util.escapeJavaScript($input.params().header.get($header))" #if($foreach.hasNext),#end
                #end
              },
              "method": "$context.httpMethod",
              "path": "$context.path",
              "queryParams": {
                #foreach($param in $input.params().querystring.keySet())
                "$param": "$util.escapeJavaScript($input.params().querystring.get($param))" #if($foreach.hasNext),#end
                #end
              },
              "pathParams": {
                #foreach($param in $input.params().path.keySet())
                "$param": "$util.escapeJavaScript($input.params().path.get($param))" #if($foreach.hasNext),#end
                #end
              },
              "stageVariables": {
                #foreach($variable in $context.stageVariables.keySet())
                "$variable": "$util.escapeJavaScript($context.stageVariables.get($variable))" #if($foreach.hasNext),#end
                #end
              },
              "requestContext": {
                "accountId": "$context.accountId",
                "apiId": "$context.apiId",
                "httpMethod": "$context.httpMethod",
                "identity": {
                  "accessKey": "$context.identity.accessKey",
                  "accountId": "$context.identity.accountId",
                  "apiKey": "$context.identity.apiKey",
                  "caller": "$context.identity.caller",
                  "cognitoAuthenticationProvider": "$context.identity.cognitoAuthenticationProvider",
                  "cognitoAuthenticationType": "$context.identity.cognitoAuthenticationType",
                  "cognitoIdentityId": "$context.identity.cognitoIdentityId",
                  "cognitoIdentityPoolId": "$context.identity.cognitoIdentityPoolId",
                  "sourceIp": "$context.identity.sourceIp",
                  "user": "$context.identity.user",
                  "userAgent": "$context.identity.userAgent",
                  "userArn": "$context.identity.userArn"
                },
                "path": "$context.path",
                "protocol": "$context.protocol",
                "requestId": "$context.requestId",
                "requestTime": "$context.requestTime",
                "requestTimeEpoch": "$context.requestTimeEpoch",
                "resourceId": "$context.resourceId",
                "resourcePath": "$context.resourcePath",
                "stage": "$context.stage"
              }
            }
        responses:
          default:
            statusCode: '200'
            responseTemplates:
              application/json: $input.json('$.body')

components:
  schemas:
    Error:
      type: object
      properties:
        error:
          type: string
          description: Error message
          example: 'Internal server error'
        statusCode:
          type: integer
          description: HTTP status code
          example: 500
        timestamp:
          type: string
          format: date-time
          description: Error timestamp
          example: '2024-01-15T10:30:00Z'
      required:
        - error
        - statusCode
        - timestamp

    Project:
      type: object
      properties:
        projectId:
          type: string
          description: The unique identifier of the project
          example: 'proj_1234567890'
        name:
          type: string
          description: The name of the project
          example: 'My Project'
        description:
          type: string
          description: The description of the project
          example: 'A description of my project'
        status:
          type: string
          enum: ['ACTIVE', 'SUSPENDED']
          description: The status of the project
          example: 'ACTIVE'
        preferences:
          type: object
          description: The preferences of the project
          example: {}
        createdAt:
          type: integer
          description: The timestamp (milliseconds) of when the project was created
          example: 1705312800000
        updatedAt:
          type: integer
          description: The timestamp (milliseconds) of when the project was last updated
          example: 1705312800000
      required:
        - projectId
        - name
        - description
        - status
        - preferences
        - createdAt
        - updatedAt

  securitySchemes:
    ApiKeyAuth:
      type: apiKey
      in: header
      name: x-api-key
      description: API key for authentication
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
      description: JWT token for authentication

tags:
  - name: Health
    description: Health check and status endpoints
  - name: Auth
    description: Authentication and authorization endpoints
  - name: Users
    description: User management endpoints
  - name: Projects
    description: Project management endpoints

externalDocs:
  description: Find more info about Prunk Services
  url: https://github.com/your-org/prunk
